<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\Busi\SaleOrderItem;
use Illuminate\Database\Eloquent\Builder;

class SaleOrderItemController extends ApiController
{
	//
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new SaleOrderItem($attributes);
	}

	public function fillQueryForIndex(Request $request, Builder &$query)
	{
		$query->with(['material']);
		parent::fillQueryForIndex($request, $query); // TODO: Change the autogenerated stub
	}
}