<?php

namespace App\Http\Controllers\Api;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\Busi\SaleOrder;
use Illuminate\Support\Facades\DB;

class SaleOrderController extends ApiController
{
	//
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new SaleOrder($attributes);
	}

	public function fillQueryForIndex(Request $request, Builder &$query)
	{
		parent::fillQueryForIndex($request, $query); // TODO: Change the autogenerated stub
		$query->with(['store', 'items.material']);
		$query->whereExists(function($query){
			$query->select(DB::raw(1))
				->from('st_sale_order_items')
				->whereRaw('st_sale_order_items.fsale_order_id = st_sale_orders.id');
		});
	}

	public function store(Request $request)
	{
		return parent::store($request); // TODO: Change the autogenerated stub
	}

}