<?php

namespace App\Http\Controllers\Api;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\Busi\Stock;

/**
 * 库存盘点
 * Class StockController
 * @package App\Http\Controllers\Api
 */
class StockController extends ApiController
{
	//
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new Stock($attributes);
	}

	public function fillQueryForIndex(Request $request, Builder &$query)
	{
		$query->with(['material']);
		parent::fillQueryForIndex($request, $query); // TODO: Change the autogenerated stub
	}

	public function show($id)
	{
		//return parent::show($id); // TODO: Change the autogenerated stub
		$entity =$this->newEntity()->newQuery()->with(['material'])->find($id);
		return response($entity, 200);
	}

	public function store(Request $request)
	{
		return parent::store($request); // TODO: Change the autogenerated stub
	}

	public function update(Request $request, $id)
	{
		return parent::update($request, $id); // TODO: Change the autogenerated stub
	}
}