<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\Busi\StockIn;

class StockInController extends ApiController
{
	//
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new StockIn($attributes);
	}

	public function fillQueryForIndex(Request $request, Builder &$query)
	{
		$query->with(['items']);
		parent::fillQueryForIndex($request, $query); // TODO: Change the autogenerated stub
		$userId = $request->input('user_id',0);
		if($userId > 0){
			$user = User::find($userId);
			if($user->reference_type == 'employee' && $user->reference->customers->count() > 0){
				$ids = $user->reference->customers->map(function ($item){
					return $item->id;
				});
				$query->whereIn('fcust_id', $ids);
			}else if($user->reference_type == 'customer'){
				$query->where('fcust_id', $user->reference_id);
			}
		}
	}
}