<?php

namespace App\Http\Controllers\Api;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Busi\VisitStoreCalendar;


class VisitStoreCalendarController extends ApiController
{
    //
    public function newEntity(array $attributes = [])
    {
        // TODO: Implement newEntity() method.
        return new VisitStoreCalendar($attributes);
    }

    public function fillQueryForIndex(Request $request, Builder &$query)
    {
	    parent::fillQueryForIndex($request, $query); // TODO: Change the autogenerated stub
	    $query->with(['store.customer', 'employee']);
    }
}
