<?php
namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Customer\BaseController;
use App\Models\Busi\StockCheck;
use Illuminate\Support\Facades\Auth;

class StockCheckController extends BaseController
{
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new StockCheck($attributes);
	}

	/**
	* Display a listing of the resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function index()
	{
		//
		return view('customer.stock-check.index');
	}

	/**
	* Show the form for creating a new resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function create()
	{
		return view('customer.stock-check.create');
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function edit($id)
	{
		$entity = StockCheck::find($id);
		return view('customer.stock-check.edit', ['entity' => $entity]);
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
    public function show($id)
    {
        $entity = $this->newEntity()->newQuery()->find($id);
        $image_ids = [];
        if (!empty($entity->fphotos)){
            $image_ids = explode(',',$entity->fphotos);
        }

        $images = [];
        foreach ($image_ids as $image_id){
            $images[] = '/admin/show-image?imageId='.$image_id;
        }

        return view('admin.stock-check.show',['images' => $images]);

    }

    public function entityQuery()
    {
        $customer = Auth::user()->reference;
        return StockCheck::query()->where('fcust_id',$customer->id); // TODO: Change the autogenerated stub
    }

    /**
	* @param  Request $request
	* @param  array $searchCols
	* @param  array $with
	* @param  null $conditionCall
	* @param  bool $all_columns
	* @return  \Illuminate\Http\JsonResponse
	*/
	public function pagination(Request $request, $searchCols = [], $with=[], $conditionCall = null, $all_columns = false){
		$searchCols = ["fphotos"];
		return parent::pagination($request, $searchCols);
	}

}
