<?php
/**
 * Created by PhpStorm.
 * User: john
 * Date: 2017-05-08
 * Time: 15:03
 */

namespace App\Services\DataSync;


use App\Models\Busi\Customer;
use App\Models\User;

class CustomerFilter extends DefaultFilter
{
	public function afterAccept(&$data)
	{
		//parent::afterAccept($data); // TODO: Change the autogenerated stub
		$customer = Customer::find($data['id']);
		if (!empty($customer)) {
			if(empty($customer->user)) {
				$customer->user()->create([
					'name' => $customer->ftel,
					'password' => md5('888888'),
					'status' => 1,
					'nick_name' => $customer->fname,
				]);
			}else{
				$customer->user()->update([
					'name' => $customer->ftel,
					//'password' => md5('888888'),
					'status' => 1,
					'nick_name' => $customer->fname,
				]);
			}
		}else{
			$user = User::where('reference_id', $data['id'])->where('reference_type', 'customer')->first();
			if(!empty($user)){
				$user->delete();
			}
		}
	}
}
