<?php
/**
 * Created by PhpStorm.
 * User: john
 * Date: 2017-03-11
 * Time: 18:45
 */

namespace App\Services\DataSync;


use App\Models\Busi\DisplayPolicy;

class DisplayPolicyStoreFilter extends DefaultFilter
{
	public function beforeSend(&$data)
	{
		//parent::beforeSend($data); // TODO: Change the autogenerated stub
		if(isset($data['fpolicy_id'])) {
			$policy = DisplayPolicy::find($data['fpolicy_id']);
			if(!empty($policy)){
				$data['fpolicy_bill_no'] = $policy->fbill_no;
			}
		}
	}
}