<?php
/**
 * Created by PhpStorm.
 * User: john
 * Date: 2017-04-27
 * Time: 17:10
 */

namespace App\Services\DataSync;

use EmployeeRepo;

class EmployeeFilter extends DefaultFilter
{
	public function afterAccept(&$data)
	{
		//parent::afterAccept($data); // TODO: Change the autogenerated stub
		if(!empty($data['fphone'])) {
			EmployeeRepo::clearCache($data['fphone']);
		}
	}
}