<?php
/**
 * Created by PhpStorm.
 * User: john
 * Date: 2017-05-08
 * Time: 15:03
 */

namespace App\Services\DataSync;


use App\Models\Busi\StockIn;
use App\Services\MessageService;

class StockInFilter extends DefaultFilter
{
	public function afterAccept(&$data)
	{
		//parent::afterAccept($data); // TODO: Change the autogenerated stub
		$stockIn = StockIn::find($data['id']);
		if (!empty($stockIn->customer) && !empty($stockIn->customer->user)) {
			MessageService::Instance()->systemSend(
				$stockIn->customer->user->id,
				'您有一条到货确认消息',
				'您有一条到货确认消息',
				false,
				$stockIn->id,
				'stock_in'
			);
		}

	}
}
