<link rel="stylesheet" href="/assets/plugins/datatables/css/dataTables.bootstrap.min.css" />
<link rel="stylesheet" href="/assets/plugins/datatables/extensions/Buttons/css/buttons.dataTables.min.css" />
<link rel="stylesheet" href="/assets/plugins/datatables/extensions/Buttons/css/buttons.bootstrap.min.css" />
<link rel="stylesheet" href="/assets/plugins/datatables/extensions/Select/css/select.dataTables.min.css" />
<link rel="stylesheet" href="/assets/plugins/datatables/extensions/Select/css/select.bootstrap.min.css" />
<link rel="stylesheet" href="/assets/plugins/datatables/extensions/Editor/css/editor.bootstrap.min.css" />
{{--<link rel="stylesheet" href="/assets/plugins/datatables/extensions/AutoFill/css/autoFill.bootstrap.min.css" />--}}
<link rel="stylesheet" href="/assets/plugins/datatables/extensions/Responsive/css/responsive.bootstrap.min.css" />
<link rel="stylesheet" href="/assets/plugins/jquery-datatables-checkboxes-1.1.3/css/dataTables.checkboxes.css" />