<?php

namespace App\Models\Busi;

use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    protected $guarded = ['id'];
    public $fieldNames = [];

    /**
     * The name of the "created at" column.
     *
     * @var string
     */
    const CREATED_AT = 'fcreate_date';

    /**
     * The name of the "updated at" column.
     *
     * @var string
     */
    const UPDATED_AT = 'fmodify_date';


	/**
	 *
	 */
	protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($model){
            event(new \App\Events\ModelCreatedEvent($model));
        });
        static::deleted(function ($model){
            event(new \App\Events\ModelDeletedEvent($model));
        });
        static::updated(function ($model){
            event(new \App\Events\ModelUpdatedEvent($model));
        });
    }


}
