<?php

namespace App\Models\Busi;

use Illuminate\Database\Eloquent\Model;

/**
 * model description
 * Class StockOutItem
 * @package  App\Models
 *
 * @author  xrs
 * @SWG\Model(id="StockOutItem")
 * @SWG\Property(name="box_qty", type="number", description="箱数量")
 * @SWG\Property(name="bottle_qty", type="number", description="瓶数量")
 * @SWG\Property(name="present_box_qty", type="number", description="赠送的箱数量")
 * @SWG\Property(name="present_bottle_qty", type="number", description="赠送的瓶数量")
 * @SWG\Property(name="fbase_qty", type="number", description="销售基本单位数量（瓶）(订单数量*商品表FRotio)")
 * @SWG\Property(name="fbase_unit", type="string", description="基本单位")
 * @SWG\Property(name="fcreate_date", type="string", description="创建时间")
 * @SWG\Property(name="fcreator_id", type="integer", description="创建人")
 * @SWG\Property(name="fdocument_status", type="string", description="审核状态")
 * @SWG\Property(name="fmaterial_id", type="integer", description="物料内码id")
 * @SWG\Property(name="fmodify_date", type="string", description="修改时间")
 * @SWG\Property(name="fmodify_id", type="integer", description="修改人")
 * @SWG\Property(name="fqty", type="float", description="订单数量")
 * @SWG\Property(name="fsale_unit", type="string", description="销售单位")
 * @SWG\Property(name="fstock_out_id", type="integer", description="出库ID")
 * @SWG\Property(name="id", type="integer", description="")
 * @SWG\Property(name="fprice_box", type="float", description="单价/箱")
 * @SWG\Property(name="fprice_bottle", type="float", description="单价/瓶")
 * @SWG\Property(name="famount", type="number", description="金额")
  */
class StockOutItem extends BaseModel
{
	//
	protected $table = 'st_stock_out_items';
	protected $guarded = ['id'];

    public function stockout(){
        return $this->hasOne(StockOut::class,'id','fstock_out_id');
    }

    public function material(){
        return $this->hasOne(Material::class,'id','fmaterial_id');
    }

    protected static function boot()
    {
	    parent::boot(); // TODO: Change the autogenerated stub

	    static::updating(function ($model){
			$model->famount = $model->fprice_box * $model->box_qty + $model->fprice_bottle * $model->bottle_qty;
	    });
    }
}
