<?php

namespace App\Models\Busi;

use Illuminate\Database\Eloquent\Model;


class VisitLineStore extends BaseModel
{
    //
	 protected $table = 'visit_line_store';

	 protected $guarded = ['id'];

    public $filter = true;
	 
	 public function employee(){
	 	return $this->hasOne(Employee::class, 'id', 'femp_id');
	 }
	 
	 public function line(){
	 	return $this->hasOne(VisitLine::class, 'id', 'fline_id');
	 }

	 public function store(){
         return $this->hasOne(Store::class, 'id', 'fstore_id');
     }

    public function adminFilter($queryBuilder, $request)
    {
        //return parent::adminFilter($queryBuilder, $request); // TODO: Change the autogenerated stub
        $data = $request->all();
        if (!empty($data['tree'])){
            $emp = Employee::find($data['tree']['nodeid']);
            if (empty($emp)) {
                $dept = Department::find($data['tree']['nodeid']);
                $emp_ids = $dept->getAllEmployeeByDept()->pluck('id')->toArray();

                $queryBuilder->whereIn('femp_id', $emp_ids);
            } else {
                $queryBuilder->where('femp_id', $data['tree']['nodeid']);
            }
        }

        if (!empty($data['distinct'])){
            $queryBuilder->groupBy($data['distinct'])->distinct();
        }

        if (!empty($data['init_filter'])){
            if (!empty($data['init_filter']['femp_id'])){
                $queryBuilder->where('femp_id', $data['init_filter']['femp_id']);
            }

            if (!empty($data['init_filter']['fline_id'])){
                $queryBuilder->where('fline_id', $data['init_filter']['fline_id']);
            }
        }

        if (!empty($data['filter'])){
            foreach ($data['filter'] as $f){
                $filter_name = $f['name'];
                if ($filter_name=="distinctfields"&&!empty($f['value'])){
                    $distinct = explode(",",$f['value']);
                    $queryBuilder->groupBy($distinct)->distinct();
                }elseif ($filter_name=="femp"&&!empty($f['value'])){
                    $ids = Employee::query()->where('fname','like','%'.$f['value'].'%')->pluck('id');
                    $queryBuilder->whereIn('femp_id', $ids);
                }elseif ($filter_name=="fstore"&&!empty($f['value'])){
                    $ids = Store::query()->where('ffullname','like','%'.$f['value'].'%')->pluck('id');
                    $queryBuilder->whereIn('fstore_id', $ids);
                }elseif ($filter_name=="fcontracts"&&!empty($f['value'])){
                    $ids = Store::query()->where('fcontracts','like','%'.$f['value'].'%')->pluck('id');

                    $queryBuilder->whereIn('fstore_id', $ids);
                }else{
                    $queryBuilder=$this->adminFilterQuery($queryBuilder,$f);
                }
            }
        }


        return $queryBuilder;
    }
}
