<?php

namespace App\Models\Busi;

use Illuminate\Database\Eloquent\Model;

/**
 * 拍照备注
 * Class VisitPzbz
 * @package App\Models\Busi
 * @author xrs
 * @SWG\Model(id="VisitPzbz")
 * @SWG\Property(name="created_at", type="string", description="")
 * @SWG\Property(name="fbill_no", type="string", description="bill no")
 * @SWG\Property(name="flog_id", type="integer", description="visit_todo_calendar id")
 * @SWG\Property(name="fphoto_id", type="integer", description="picture id")
 * @SWG\Property(name="fremark", type="string", description="备注")
 * @SWG\Property(name="id", type="integer", description="")
 * @SWG\Property(name="updated_at", type="string", description="")
 */
class VisitPzbz extends BaseModel
{
    //
	protected $table='visit_pzbz';

	public function todo_calendar(){
		return $this->belongsTo(VisitTodoCalendar::class, 'flog_id');
	}

	protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub

		static::created(function($entity){
			if (!empty($entity->todo_calendar->todo->fname) && $entity->todo_calendar->todo->fname == '正常陈列') {
				Rollcall::createOrUpdate([
					'femp_id' => $entity->todo_calendar->femp_id,
					'faddress' => $entity->todo_calendar->store_calendar->store->faddress,
					'flongitude' => $entity->todo_calendar->flongitude,
					'flatitude' => $entity->todo_calendar->flatitude,
					'fphotos' => $entity->fphotos,
					'fmode' => 2
				]);
			}
		});

		static::updated(function($entity){
			if (!empty($entity->todo_calendar->todo->fname) && $entity->todo_calendar->todo->fname == '正常陈列') {
				Rollcall::createOrUpdate([
					'femp_id' => $entity->todo_calendar->femp_id,
					'faddress' => $entity->todo_calendar->store_calendar->store->faddress,
					'flongitude' => $entity->todo_calendar->flongitude,
					'flatitude' => $entity->todo_calendar->flatitude,
					'fphotos' => $entity->fphotos,
					'fmode' => 2
				]);
			}
		});
	}
}
