<?php

namespace App\Models\Busi;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

/**
 * model description
 * 工作流定义
 * @package  App\Models
 *
 * @author  xrs
 * @SWG\Model(id="WorkFlow")
 * @SWG\Property(name="name", type="string", description="名称")
 * @SWG\Property(name="status", type="integer", description="状态（0-未启用, 1-启用）")
 * @SWG\Property(name="table", type="string", description="关联表名")
 * @SWG\Property(name="created_at", type="string", description="")
 * @SWG\Property(name="updated_at", type="string", description="")
 * @SWG\Property(name="id", type="integer", description="")
  */
class WorkFlow extends Model
{
	//
	protected $table = 'work_flows';
	protected $guarded = ['id'];

	/**
	 * 流程实例
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function instances(){
		return $this->hasMany(WorkFlowInstance::class, 'work_flow_id');
	}

	/**
	 * 数据变量
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function variables(){
		return $this->hasMany(WorkFlowVariable::class, 'work_flow_id');
	}

	/**
	 * 任务缺省处理人
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function default_task_approver(){
		return $this->belongsTo(User::class, 'default_task_approver_id');
	}

	protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
		static::creating(function ($model){
			$model->uid = uuid();
		});
	}

}
