<?php
namespace App\Http\Controllers\Admin;

use App\Models\Busi\Resources;
use Illuminate\Http\Request;
use App\Http\Controllers\Admin\AdminController;
use App\Models\Busi\Carousel;

class CarouselController extends AdminController
{
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new Carousel($attributes);
	}

	/**
	* Display a listing of the resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function index()
	{
		//
		return view('admin.carousel.index');
	}

	/**
	* Show the form for creating a new resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function create()
	{
		return view('admin.carousel.create');
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function edit($id)
	{
		$entity = Carousel::find($id);
		return view('admin.carousel.edit', ['entity' => $entity]);
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function show($id)
	{
		//
	}

	/**
	* @param  Request $request
	* @param  array $searchCols
	* @param  array $with
	* @param  null $conditionCall
	* @param  bool $all_columns
	* @return  \Illuminate\Http\JsonResponse
	*/
	public function pagination(Request $request, $searchCols = [], $with=[], $conditionCall = null, $all_columns = false){
		$searchCols = ["fname"];
		return parent::pagination($request, $searchCols);
	}

	public function store(Request $request, $extraFields = [])
	{
		$action = $request->input('action', 'upload');
		if($action == 'upload') {
			//return parent::store($request, $extraFields); // TODO: Change the autogenerated stub
			$res = $this->uploadImg($request);
			return response()->json($res);
		}else{
			return parent::store($request, $extraFields);
		}
	}

	public function update(Request $request, $id, $extraFields = [])
	{
		$action = $request->input('action', 'upload');
		if($action == 'upload') {
			//return parent::store($request, $extraFields); // TODO: Change the autogenerated stub
			$res = $this->uploadImg($request);
			return response()->json($res);
		}else{
			return parent::update($request, $id, $extraFields);
		}
	}

	protected function uploadImg($request)
	{
		//upload
		$file = $request->file('upload');
		//var_dump($file);
		if($file->isValid())
		{
			$path = $file->store('upload/images');
			if($path){
				$res = Resources::create([
					'name' => $file->getClientOriginalName(),
					'ext' => $file->getClientOriginalExtension(),
					'size' => $file->getSize(),
					'path' => 'app/' . $path ,
					'mimetype' => $file->getMimeType(),
				]);
				return ['data' => [], 'files' => ['files' => $res], 'upload' => ['id' => $res->id] ];
			}
		}
		return false;
	}
}
