<?php
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\AdminController;
use App\Models\Busi\Rollcall;

class RollcallController extends AdminController
{
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new Rollcall($attributes);
	}

	/**
	* Display a listing of the resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function index()
	{
		//
		return view('admin.rollcall.index');
	}

	/**
	* Show the form for creating a new resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function create()
	{
		return view('admin.rollcall.create');
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function edit($id)
	{
		$entity = Rollcall::find($id);
		return view('admin.rollcall.edit', ['entity' => $entity]);
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function show($id)
	{
		//
	}

	/**
	* @param  Request $request
	* @param  array $searchCols
	* @param  array $with
	* @param  null $conditionCall
	* @param  bool $all_columns
	* @return  \Illuminate\Http\JsonResponse
	*/
	public function pagination(Request $request, $searchCols = [], $with=[], $conditionCall = null, $all_columns = false){
		$searchCols = ["bd_employees.fname"];
		return parent::pagination($request, $searchCols, $with, $conditionCall, true);
	}

	public function entityQuery()
	{
		//return parent::entityQuery(); // TODO: Change the autogenerated stub
		$query  = parent::entityQuery();
		$query->select(['bd_rollcalls.*', 'bd_employees.fname as employee_name', 'bd_positions.fname as position_name'])
			->join('bd_employees', 'bd_employees.id', '=', 'bd_rollcalls.femp_id')
			->leftJoin('bd_positions', 'bd_employees.fpost_id', '=', 'bd_positions.id');
		return $query;
	}

}
